default_config:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://configurator:3218/
    require_admin: true
  nodered:
    title: Node-Red
    icon: mdi:shuffle-variant
    url: http://nodered:1880/
    require_admin: true